<?php

namespace AppBundle\Repository;

/**
 * EnArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnArticleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des articles decroissantes
     */
    public function findArticleDesc($limit,$offset)
    {
        return $this->createQueryBuilder('a')
                    ->orderBy('a.id', 'DESC')
                    ->setFirstResult($offset)
                    ->setMaxResults($limit)
                    ->getQuery()->getResult()
            ;
    }
}
