<?php

namespace AppBundle\Repository;

/**
 * EnArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnArticleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des articles decroissantes
     */
    public function findArticleDesc($limit,$offset)
    {
        return $this->createQueryBuilder('a')
                    ->orderBy('a.id', 'DESC')
                    ->setFirstResult($offset)
                    ->setMaxResults($limit)
                    ->getQuery()->getResult()
            ;
    }

    /**
     * Recherche de l'article selon son ID
     */
    public function findArticle($article)
    {
        return $this->createQueryBuilder('a')
                    ->where('a.id = :id')
                    ->setParameter('id', $article)
            ;
    }

    /**
     * Liste des articles non traduits
     */
    public function findEnArticle($article)
    {
        //die($article);
        if ($article === 'null'){
            return $this->createQueryBuilder('a')
                        ->where('a.traduction IS NULL')
                        ->orWhere('a.traduction = 0')
                        ;
        } else{
            return $this->findArticle($article);
        }
    }

    /**
     * Liste des articles pas encore traduits
     */
    public function findEnArticleNonTraduit($article)
    {
        return $this->findArticle($article)
                    ->orWhere('a.traduction IS NULL')
                    ->orWhere('a.traduction = 0')
            ;
    }

}
