<?php

namespace AppBundle\Repository;

/**
 * EnCampaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnCampaignRepository extends \Doctrine\ORM\EntityRepository
{
}
