<?php

namespace AppBundle\Repository;

/**
 * EnPresentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnPresentationRepository extends \Doctrine\ORM\EntityRepository
{
}
