<?php

namespace AppBundle\Repository;

/**
 * EnResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnResourceRepository extends \Doctrine\ORM\EntityRepository
{
}
