<?php

namespace AppBundle\Repository;

/**
 * EnTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
