<?php

namespace AppBundle\Repository;

/**
 * EnWelcomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnWelcomeRepository extends \Doctrine\ORM\EntityRepository
{
}
