<?php

namespace AppBundle\Repository;

/**
 * FrArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrArticleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste decroissantes des articles
     */
    public function boListDesc($limit, $offset)
    {
        return $this->queryArticle()
                    ->setFirstResult($offset)
                    ->setMaxResults($limit)
                    ->getQuery()->getResult()
            ;
    }

    /**
     * Recherche de l'article selon l'ID
     */
    public function findArticle($article)
    {
        return $this->createQueryBuilder('a')
                    ->where('a.id = :id')
                    ->setParameter('id', $article)
            ;
    }

    public function findFrArticle($article)
    {
        if ($article === 'null'){
            return $this->createQueryBuilder('a')
                        ->where('a.traduction IS NULL')
                        ->orWhere('a.traduction = 0')
                ;
        } else{
            return $this->findArticle($article);
        }
    }

    /**
     * Recherche des artciles pas encore traduits
     */
    public function findFrArticleNonTraduit($article)
    {
        return $this->findArticle($article)
                    ->orWhere('a.traduction IS NULL')
                    ->orWhere('a.traduction = 0')
            ;
    }

    /**
     * Fonction de recherche
     */
    public function queryArticle()
    {
        return $this->createQueryBuilder('a')
                    ->orderBy('a.id', 'DESC')
            ;
    }
}
