<?php

namespace AppBundle\Repository;

/**
 * FrArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrArticleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste decroissantes des articles
     */
    public function boListDesc($limit, $offset)
    {
        return $this->queryArticle()
                    ->setFirstResult($offset)
                    ->setMaxResults($limit)
                    ->getQuery()->getResult()
            ;
    }

    /**
     * Fonction de recherche
     */
    public function queryArticle()
    {
        return $this->createQueryBuilder('a')
                    ->orderBy('a.id', 'DESC')
            ;
    }
}
