<?php

namespace AppBundle\Repository;

/**
 * FrBienvenueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrBienvenueRepository extends \Doctrine\ORM\EntityRepository
{
}
