<?php

namespace AppBundle\Repository;

/**
 * FrCampagneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrCampagneRepository extends \Doctrine\ORM\EntityRepository
{
}
