<?php

namespace AppBundle\Repository;

/**
 * FrJobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrJobRepository extends \Doctrine\ORM\EntityRepository
{
    public function findListDESC()
    {
        return $this->list($limit = null, $offset = null)
                    ->getQuery()->getResult()
            ;
    }

    public function list($limit = null, $offset = null){
        return $this->createQueryBuilder('j')
                    ->orderBy('j.datefin', 'DESC')
            ;
    }
}
