<?php

namespace AppBundle\Repository;

/**
 * FrPresentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrPresentationRepository extends \Doctrine\ORM\EntityRepository
{
}
