<?php

namespace AppBundle\Repository;

/**
 * FrRessourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrRessourceRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste decroissante des publications
     */
    public function findRessourceDesc($limit, $offset)
    {
        return $this->createQueryBuilder('r')
                    ->orderBy('r.id', 'DESC')
                    ->setFirstResult($offset)
                    ->setMaxResults($limit)
                    ->getQuery()->getResult()
            ;
    }
}
