<?php

namespace AppBundle\Repository;

/**
 * FrSliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrSliderRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste decroissante des sliders backoffice
     */
    public function boListDesc($limit, $offset)
    {
        return $this->querySlider()
                    ->setFirstResult($offset)
                    ->setMaxResults($limit)
                    ->getQuery()->getResult()
            ;
    }

    /**
     * Fonction de requete de base
     */
    public function querySlider()
    {
        return $this->createQueryBuilder('s')
                    ->orderBy('s.id', 'DESC')
            ;
    }
}
