<?php

namespace AppBundle\Repository;

/**
 * FrTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
