<?php

namespace AppBundle\Repository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Recherche des des galleries photos
     */
    public function findGallerie($limit, $offset)
    {
        return $this->createQueryBuilder('p')
                    ->groupBy('p.article')
                    ->orderBy('p.id', 'DESC')
                    ->setFirstResult($offset)
                    ->setMaxResults($limit)
                    ->getQuery()->getResult();
            ;
    }
}
