<?php

namespace AppBundle\Repository;

/**
 * TraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraductionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Verification de l'existence de la traduction
     */
    public function findFrArticle($fr)
    {
        if (!$fr){
            return $this->createQueryBuilder('t')
                        ->addSelect('a')
                        ->innerJoin('t.francais', 'a')
                        ->where('t.francais <> a.id')
                        //->getQuery()->getResult()
                ;
        } else{
            /*return $this->createQueryBuilder()
                        ->select('a')
                        ->from('AppBundle:FrArticle', 'a')
                        ->where('a.id = :fr')
                        ->setParameter('fr', $fr)
                        ->getQuery()->getResult()
                ;*/
            $em = $this->getEntityManager();
            return $em->createQuery(
                        'SELECT a 
                              FROM AppBundle:FrArticle a
                              where a.traduction IS NULL 
                              '
                        )->getResult()
                ;
        }
    }
}
